### ISSUE TITLE
DRAKVUF: Process Injection Error

### ISSUE THREAD

**Issue by MohammadBilalArif** [tklengyel/drakvuf#25] opened 2015-11-27 17:09 UTC
When I inject any process blue screen error appear on VM and shutdown. When I try to use dynamic malware analysis, result are pasted below. Your help will be appreciated.

robot@robot:~/drakvuf/src$ sudo ./drakvuf -r win7.json -d 3

DRAKVUF v0.2

[SYSCALL] ntoskrnl.exe!NtReleaseWorkerFactoryWorker

[SYSCALL] ntoskrnl.exe!NtWaitForMultipleObjects

[SYSCALL] ntoskrnl.exe!NtReleaseWorkerFactoryWorker

[POOLMON] Io (type: NonPagedPoolExecute, size: 32): nt!io,general IO allocations

[SYSCALL] ntoskrnl.exe!NtSetTimer

[POOLMON] NDwi (type: unknown_pool_type, size: 40): ndis.sys,NDIS_TAG_WORK_ITEM

[SYSCALL] ntoskrnl.exe!NtWaitForWorkViaWorkerFactory

[POOLMON] IoUs (type: unknown_pool_type, size: 16): nt!io,I/O SubSystem completion Context Allocation

[SYSCALL] ntoskrnl.exe!NtCallbackReturn

[SYSCALL] ntoskrnl.exe!NtCallbackReturn

[SYSCALL] ntoskrnl.exe!NtCallbackReturn

[SYSCALL] ntoskrnl.exe!NtWaitForWorkViaWorkerFactory

VMI_ERROR: Caught a memory event that had no handler registered in LibVMI @ GFN 9930 (0x26ca416), access: 2

robot@robot:~/drakvuf/src$ sudo ./drakvuf -r win7.json -d 3

DRAKVUF v0.2

robot@robot:~/drakvuf/src$

**Comment by tklengyel** [comment] 2015-11-27 17:12
This is likely caused by adding more then 1 vcpu  to the guest.

**Comment by MohammadBilalArif** [comment] 2015-11-27 17:20
absolutly right. Now i changed to VCPU to 1  and every thing is working OK. Why i cannot assign more than 1, for the sake of performance?

**Comment by tklengyel** [comment] 2015-11-27 17:21
It's not supported at the moment.

**Comment by MohammadBilalArif** [comment] 2015-11-27 17:27
Live file extraction still not working. Output is:

root@robot:/home/robot/drakvuf/src# ./drakvuf -d win7.json 13
DRAKVUF v0.2
root@robot:/home/robot/drakvuf/src#

**Comment by tklengyel** [comment] 2015-11-27 17:33
The command line arguments have changed on version 0.2. Please review the
new parameter syntax by simply running drakvuf without any arguments.

**Comment by MohammadBilalArif** [comment] 2015-11-27 17:50
I could make only this command according to given format. This is showing me system calls.
sudo ./drakvuf -r win7.json -d 13 

Which command will help me in Live File extraction, or it will be appreciated if you can past  here commands for all features of DRAKVUF like this.

**Comment by MohammadBilalArif** [comment] 2015-11-27 18:38
I have not good understanding of comand line arguments, and I am trying continuously. Due to some critical reasons, I need prompt reply, I will be thankful. Request

**Comment by tklengyel** [comment] 2015-11-29 17:25
No extra command is necessary to enable file extraction if the plugin has been enabled during compile time. You should review which plugins are enabled after running ./configure. Also, if you have critical errors it would be wise to post those errors as it's pretty much impossible to help if the only thing you say is "it's not working".

Also please try to keep the issues on point. If you encounter new issues please open a separate ticket for those to aid others who may be searching for solutions to the same problem. I'm closing this ticket for now.

**Closed by tklengyel** 2015-11-29 17:25 UTC

**Comment by Preetixen** [comment] 2016-02-14 07:08
Hi I encounter an error:

after running sudo ./drakvuf -r win7.json -d 1

could you plz help


![err1](https://cloud.githubusercontent.com/assets/16998342/13032417/d7e9744c-d345-11e5-8f6d-c67116d49ba1.png)
![err2](https://cloud.githubusercontent.com/assets/16998342/13032418/d8214322-d345-11e5-825e-6d9f547acbb8.png)

**Comment by tklengyel** [comment] 2016-02-14 17:13
This is a closed ticket and your problem is unrelated to what has been discussed here. And I already pointed out in the other issue you opened what the your error is.
