### ISSUE TITLE
upgrade issue

### ISSUE THREAD

**Issue by zdzhjx** [tklengyel/drakvuf#214] opened 2016-09-13 08:58 UTC
Recently, I upgrade xen to 4.7 to use the new drakvuf version, but, when I use souce from https://github.com/tklengyel/drakvuf and follow the steps from http://drakvuf.com/, after I reboot, the machine can not start up, it go to grub infinitely.

Where I change the xen to xenproject.org version, it can boot the system OK, but if I run drakvuf, it will cost large cpu, the drakvuf can not work normally.

so, my question is which version is best to drakvuf?

thanks.

**Comment by tklengyel** [comment] 2016-09-13 19:50
You probably didn't install the `checkpolicy` package when you compiled Xen, and consequently you don't have the XSM policy compiled and installed. Make sure you follow the installation steps exactly from the start and it will work, especially if you are upgrading from a previous installation.

This is a duplicate of #213

**Closed by tklengyel** 2016-09-13 19:50 UTC
Labels: duplicate

**Comment by zdzhjx** [comment] 2016-09-14 02:59
yes, i missed checkpolicy, thanks.
