### ISSUE TITLE
Loading Initial ramdisk

### ISSUE THREAD

**Issue by Preetixen** [tklengyel/drakvuf#215] opened 2016-09-17 09:47 UTC
Hi,
We are installing current version. We installed xen4.7 .updated grub and rebooted.

However, when We restart PC, we selected Ubuntu with Xen

But system can't proceed and hangs with a message on boo time: 
Loading Initial ramdisk....

please help

**Comment by tklengyel** [comment] 2016-09-17 14:49
Please follow the installation instructions exactly from the website. You likely didn't install checkpolicy and the xsm policy file is missing required for the latest version.

**Comment by tklengyel** [comment] 2016-09-17 14:50
This is a duplicate of #213

**Closed** 2016-10-31 10:46 UTC
Labels: duplicate
