### ISSUE TITLE
injector will crash the target process

### ISSUE THREAD

**Issue by zdzhjx** [tklengyel/drakvuf#186] opened 2016-07-15 03:25 UTC
When I use injector to run my test program, I specified explorer.exe to inject, sometimes it will make explorer.exe crash,sometimes ok. 

then I made some debug on it, found that if the crash occurred,  the function injector_int3_cb in brach 'return path from CreateProcessA ' not invoked.  maybe the trap in rip is unstable? which make explorer.exe crashed on stackhash  error.

603 
604     vmi_set_vcpureg(injector->vmi, injector->createprocessa, RIP, info->vcpu);
605 
606     injector->bp.type = BREAKPOINT;
607     injector->bp.name = "ret";
608     injector->bp.cb = injector_int3_cb;
609     injector->bp.data = injector;
610     injector->bp.breakpoint.lookup_type = LOOKUP_DTB;
611     injector->bp.breakpoint.dtb = info->regs->cr3;
612     injector->bp.breakpoint.addr_type = ADDR_VA;
613     injector->bp.breakpoint.addr = info->regs->rip;   // sometime this trap not work ????
614 
615     if ( !drakvuf_add_trap(injector->drakvuf, &injector->bp) )
616         fprintf(stderr, "Failed to trap return location of injected function call @ 0x%lx!\n",
617                 injector->bp.breakpoint.addr);

drakvuf is the latest version, guest os is win7 thinpc.

Thanks.

**Comment by tklengyel** [comment] 2016-07-15 03:44
I think this is a duplicate of #158. Unfortunately it's hard to reliably reproduce the issue so figuring out the root cause is not trivial.

**Closed** 2016-07-18 16:17 UTC
Labels: duplicate
